---
- name: Ensure osv-scanner and offline vuln DB are present (controller)
  hosts: localhost
  become: true
  gather_facts: false
  roles:
    - role: osv_download

- name: Collect Python dependencies and audit with OSV (offline)
  hosts: all
  gather_facts: false
  roles:
    - role: osv_scan
...
